mysite/mysite/urls.py
from django.conf.urls import include, url # don't forget to include include
from django.contrib import admin

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
# ]

urlpatterns = [
    url( r'^myupload/', include('myupload.urls') ),
    url( r'^admin/',    admin.site.urls )
]

mysite/myupload/urls.py
# this file was added by user, not created by manage.py

from django.conf.urls import url
from . import views

app_name='myupload'

urlpatterns = [
    url( r'^$', views.index, name='index'),
    url( r'^index', views.index, name='index'),
    url( r'^list',  views.list, name='list'),
    url( r'^(?P<file_id>[0-9]+)/detail/', views.detail, name='detail' ),
    url( r'^test/(?P<something>[a-z0-9]+)', views.test, name='test' ),
    url( r'^upload_file',  views.upload_file,   name='upload_file' ),
    url( r'^upload_2file', views.upload_file_2, name='upload_file_2' ),
]

mysite/myupload/models.py
from django.db import models

# Create your models here.


class file(models.Model):
    file_name       = models.CharField(max_length=200)
    upload_datetime = models.DateTimeField('Date uploaded.')
    comment         = models.CharField(max_length=5000)

    def __str__(self):
        return '{} / {}'.format(
            self.file_name,
            self.upload_datetime,
        )

mysite/myupload/forms.py
# based on https://docs.djangoproject.com/en/1.11/topics/http/file-uploads/

from django import forms

class UploadFileForm(forms.Form):
    # title         = forms.CharField(max_length=50)
    file            = forms.FileField(
        label    ='Please select a file.',
        required =True
    )
    
    upload_datetime = forms.DateTimeField(
        label    ='Enter date manually... for now.',
        widget   =forms.SelectDateWidget(),
        required =True
    )

    comment         = forms.CharField(
        label      ='Comment.',
        widget     =forms.Textarea,
        max_length =100,
    )

mysite/myupload/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse, Http404
from django.template import loader
from .models import file

# based on https://docs.djangoproject.com/en/1.11/topics/http/file-uploads/
from .forms import UploadFileForm

# based on https://stackoverflow.com/questions/3702465/how-to-copy-inmemoryuploadedfile-object-to-disk
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.conf import settings
import io, os


def index(req):
    # return HttpResponse('Hi, this is the upload page to be built.')
    template = loader.get_template('myupload/index.html')

    number_of_files = len(file.objects.all())
    context = {
        'number_of_files': number_of_files,
    }
    return HttpResponse(template.render(context, req))

def list(req):
    # response = 'There are {} records of uploads.'
    # return HttpResponse(response.format('999'))

    # latest_files = file.objects.order_by('-upload_datetime')[:10]
    # latest_files = file.objects.order_by('-upload_datetime')
    latest_files = file.objects.order_by('-id')

    template = loader.get_template('myupload/list.html')

    context = {
        'latest_files': latest_files
    }
    return HttpResponse(template.render(context, req))

def detail(req, file_id):

    try:
        x = file.objects.get(pk=file_id)
    except file.DoesNotExist:
        raise Http404('File {} does not exist.'.format(file_id))
        
    template = loader.get_template('myupload/detail.html')
    context = {'file': x}
    return HttpResponse(template.render(context, req))


def test(req, something):
    # a view that receives something thru a GET request.
    response = 'I got {} passed by GET request!'
    return HttpResponse(response.format(something))


def upload_file(req):

    # template = loader.get_template('myupload/upload_file.html')

    if req.method=='POST':
        form = UploadFileForm(req.POST, req.FILES)
        # so, looks like I just pass FILES object to the class form.
        # Looks like I'm creating a form populating user input...
        if form.is_valid():

            # # if form is valid, do something to data given
            # new_file = file.objects.create(
            #     file_name       = req.FILES['file'].name,
            #     upload_datetime = req.POST['upload_datetime'],
            #     comment         = req.POST['comment'],
            # )

            # form = UploadFileForm()
            # context = {'form': form}
            # return render(req, 'myupload/upload_file.html', context)

            import xlsxwriter
            import re

            # prepare excel file
            output    = io.BytesIO()
            workbook  = xlsxwriter.Workbook(output, {'in_memory': True})
            worksheet = workbook.add_worksheet()

            # gain data from uploaded file

            # # obtain type
            # x = type(req.FILES['file'])
            # return HttpResponse(str(x))
            # # this returns '<class 'django.core.files.uploadedfile.TemporaryUploadedFile'>'

            # # obtain charset
            # x = req.FILES['file'].charset()
            # return HttpResponse(str(x)) # this returns None

            # # obtain encoding
            # x = req.FILES['file'].encoding
            # return HttpResponse(x)
            # # this returns error
            # # AttributeError at /myupload/upload_file
            # # '_io.BufferedRandom' object has no attribute 'encoding'

            # import chardet
            # charset = chardet.detect(req.FILES['file'])
            # return HttpResponse(charset) # error, TypeError

            # import chardet
            # charset = chardet.detect(req.FILES['file'].read())
            # return HttpResponse(charset) # don't understand the return value

            # based on https://stackoverflow.com/questions/1699126/unicodedecodeerror-with-djangos-request-files/1699299#
            encodings = ('utf-8', 'shift-jis', 'cp932')
            # encodings = ('utf-8', 'utf-8')
            for ec in encodings:

                try:
                    for row_count, row in enumerate(req.FILES['file']):

                        # do something to it

                        # row is bytes. convert it to string
                        # worksheet.write( row_count, 0, row.decode() )
                        # # also use rstrip() to remove new line at the end
                        # worksheet.write(row_count, 0, row.decode(encoding=ec).rstrip())
                        row = row.decode(encoding=ec)
                        row = row.split(',')

                        for item_count, item in enumerate(row):
                            worksheet.write(row_count, item_count, item.rstrip())

                except UnicodeDecodeError:
                    pass


            workbook.close()
            excel_data = output.getvalue()

            file_name = req.FILES['file'].name
            file_name = re.sub(
                '\.[a-zA-Z]+$',
                '.xlsx',
                file_name
            )

            response = HttpResponse(content_type='application/vnd.ms-excel')
            response['Content-Disposition'] = 'attachment; filename={}'.format(
                file_name
            )
            response.write(excel_data)

            return response

        # else:
        #     return HttpResponse(req.FILES['file'].name)

    else:
        # if this is not a POST method, just show empty form
        # .... is my understanding
        form = UploadFileForm()

        context = {'form': form}

        # so I have to pass this form to 'upload_file.html'
        # return HttpResponse(template.render(context, req))
        # return render(req, template, context)
        return render(req, 'myupload/upload_file.html', context)

def upload_file_2(req):

    # template = loader.get_template('myupload/upload_file.html')

    if req.method=='POST':
        form = UploadFileForm(req.POST, req.FILES)
        # so, looks like I just pass FILES object to the class form.
        # Looks like I'm creating a form populating user input...
        if form.is_valid():

            import xlsxwriter
            import re

            # prepare excel file
            output    = io.BytesIO()
            workbook  = xlsxwriter.Workbook(output, {'in_memory': True})
            worksheet = workbook.add_worksheet()

            # save file onto disk
            data = req.FILES['file']
            file_name = req.FILES['file'].name
            path = default_storage.save(
                os.path.join('tmp', file_name),
                ContentFile(data.read())
            )
            tmp_file = os.path.join(settings.MEDIA_ROOT, path)

            import csv

            encodings = ('utf-8', 'shift-jis', 'cp932')
            # encodings = ('utf-8', 'utf-8')
            for ec in encodings:

                try:
                    with open(tmp_file, encoding=ec) as csvfile:
                        csvreader = csv.reader(csvfile)
                        for row_count, row in enumerate(csvreader):

                            for item_count, item in enumerate(row):
                                worksheet.write(row_count, item_count, item.rstrip())

                except UnicodeDecodeError:
                    pass

            workbook.close()
            excel_data = output.getvalue()

            file_name = req.FILES['file'].name
            file_name = re.sub(
                '\.[a-zA-Z]+$',
                '.xlsx',
                file_name
            )

            response = HttpResponse(content_type='application/vnd.ms-excel')
            response['Content-Disposition'] = 'attachment; filename={}'.format(
                file_name
            )
            response.write(excel_data)

            return response

        # else:
        #     return HttpResponse(req.FILES['file'].name)

    else:
        # if this is not a POST method, just show empty form
        # .... is my understanding
        form = UploadFileForm()

        context = {'form': form}

        # so I have to pass this form to 'upload_file.html'
        # return HttpResponse(template.render(context, req))
        # return render(req, template, context)
        return render(req, 'myupload/upload_file_2.html', context)

mysite/myupload/templates/myupload/detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Django File Upload</title>
    </head>

    <body>

	<p>
	    <a href="{% url 'myupload:index' %}">Home</a>
	    <a href="{% url 'myupload:list' %}">List</a>
	    <a href="{% url 'myupload:upload_file' %}">Upload File</a>
	</p>

	{% if file %}
	<ul>
	    <li>{{ file.id }}</li>
	    <li>{{ file.file_name }}</li>
	    <li>{{ file.comment }}</li>
	    <li>{{ file.upload_datetime }}</li>
	    
	</ul>
	{% else %}
	
	<p>No polls are available.</p>
	{% endif %}

    </body>

</html>

mysite/myupload/templates/myupload/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Django File Upload</title>
    </head>

    <body>

	<p>
	    <a href="{% url 'myupload:index' %}">Home</a>
	    <a href="{% url 'myupload:list' %}">List</a>
	    <a href="{% url 'myupload:upload_file' %}">Upload File</a>
	</p>

	<p>Hi! This is generated from template!</p>

	<p>There are <a href="{% url 'myupload:list' %}">{{ number_of_files }} files</a> uploaded.</p>
    </body>

</html>

mysite/myupload/templates/myupload/list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Django File Upload</title>
    </head>

    <body>

	<p>
	    <a href="{% url 'myupload:index' %}">Home</a>
	    <a href="{% url 'myupload:upload_file' %}">Upload File</a>
	</p>

	{% if latest_files %}
	<table>
	    <tr>
		<th>ID</th>
		<th>File Name</th>
		<th>Upload Date</th>
		<th>Comment</th>
	    </tr>
	    
	    {% for f in latest_files %}
	    <tr>
		<td>{{ f.id }}</td>
		<td><a href="{% url 'myupload:detail' f.id %}">{{ f.file_name }}</a></td>
		<td>{{ f.upload_datetime }}</td>
		<td>{{ f.comment }}</td>
	    </tr>
	    {% endfor %}
	    
	</table>
	{% else %}

	<p>No files are available.</p>
	{% endif %}

    </body>

</html>

mysite/myupload/templates/myupload/upload_file.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Django File Upload</title>
    </head>

    <body>

	<p>
	    <a href="{% url 'myupload:index' %}">Home</a>
	    <a href="{% url 'myupload:list' %}">List</a>
	</p>

        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url 'myupload:upload_file' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

	    {% if form.non_field_errors %}
            <p>{{ form.non_field_errors }}</p>
	    {% endif %}

            <p>{{ form.file.label_tag }} {{ form.file.help_text }}</p>
	    <p>Upload Date Time: <input type="text" name="upload_datetime" /></p>
	    <p>Comment: <input type="text" name="comment" /></p>

            <p>
                {{ form.file.errors }}
                {{ form.file }}
            </p>

            <p><input type="submit" value="Upload"/></p>

	</form>
    </body>

</html>

mysite/myupload/templates/myupload/upload_file_2.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Django File Upload</title>
    </head>

    <body>

	<p>
	    <a href="{% url 'myupload:index' %}">Home</a>
	    <a href="{% url 'myupload:list' %}">List</a>
	    <a href="{% url 'myupload:upload_file' %}">Upload File</a>
	</p>

        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url 'myupload:upload_file_2' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

	    {% if form.non_field_errors %}
            <p>{{ form.non_field_errors }}</p>
	    {% endif %}

            <p>{{ form.file.label_tag }} {{ form.file.help_text }}</p>
	    <p>Upload Date Time: <input type="text" name="upload_datetime" /></p>
	    <p>Comment: <input type="text" name="comment" /></p>

            <p>
                {{ form.file.errors }}
                {{ form.file }}
            </p>

            <p><input type="submit" value="Upload"/></p>

	</form>
    </body>

</html>